name: create sheilds.io badge
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  create-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Get version
        id: get_ver
        working-directory: ./
        run: |
          echo "APP_VERSION=$(jq -r '.version' ./package.json)" >> $GITHUB_OUTPUT
      - name: Create Version Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.AKTIONS_LEARNING_PATHWAY }}
          gistID: 006e759541874b2bc1b300078ad2a8b1
          filename: aktions_learning_pathway.json # Use test.svg if you want to use the SVG mode.
          forceUpdate: true
          label: Version
          message: ${{ steps.get_ver.outputs.APP_VERSION }}
          color: green
